FROM golang:1.27.1-alpine3.24@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS helm-source

RUN apk add --no-cache git bash
WORKDIR /source
ADD --checksum=sha256:e884ba1241f6a7dbb8de62848f5dd4d971c5a64b4916e5ff711295d969e8c400 https://codeload.github.com/helm/helm/tar.gz/05fa37973dc9e42b76e1d2883494c87174b6074f /tmp/helm.tar.gz
RUN tar -xzf /tmp/helm.tar.gz --strip-components=1 && rm /tmp/helm.tar.gz

FROM helm-source AS helm-builder

COPY patches/helm-4.1.4-go127.patch /tmp/helm.patch
RUN git apply --check --whitespace=error-all /tmp/helm.patch && git apply /tmp/helm.patch

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    go get golang.org/x/crypto@v0.57.0 golang.org/x/net@v0.59.0 golang.org/x/text@v0.42.0 oras.land/oras-go/v2@v2.6.2 && \
    go mod tidy && \
    go test ./internal/version ./pkg/registry ./pkg/strvals ./pkg/engine ./pkg/chart/... && \
    go test ./pkg/cmd -run '^TestShortVersionBuildMetadata$' \
      -ldflags '-X helm.sh/helm/v4/internal/version.metadata=zapravila.20261006 -X helm.sh/helm/v4/internal/version.gitCommit=05fa37973dc9e42b76e1d2883494c87174b6074f' && \
    CGO_ENABLED=0 go build -trimpath -mod=readonly \
      -ldflags '-s -w -X helm.sh/helm/v4/internal/version.version=v4.1.4 -X helm.sh/helm/v4/internal/version.metadata=zapravila.20261006 -X helm.sh/helm/v4/internal/version.gitCommit=05fa37973dc9e42b76e1d2883494c87174b6074f -X helm.sh/helm/v4/internal/version.gitTreeState=dirty' \
      -o /out/helm ./cmd/helm

FROM golang:1.27.1-alpine3.24@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS helmfile-builder

RUN apk add --no-cache git bash
WORKDIR /source
ADD --checksum=sha256:b5a02fc8be34751f903af6fa621021462988d1ed13319f6e6cae95299b5c3dde https://codeload.github.com/helmfile/helmfile/tar.gz/226c16b88e2a1982b89b9ce2aee4fc69a3e03d73 /tmp/helmfile.tar.gz
RUN tar -xzf /tmp/helmfile.tar.gz --strip-components=1 && rm /tmp/helmfile.tar.gz
COPY --from=helm-builder /out/helm /usr/local/bin/helm

RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build \
    go get golang.org/x/crypto@v0.57.0 golang.org/x/net@v0.59.0 golang.org/x/text@v0.42.0 oras.land/oras-go/v2@v2.6.2 && \
    go mod tidy && \
    go test ./pkg/helmexec && \
    CGO_ENABLED=0 go build -trimpath -mod=readonly \
      -ldflags '-s -w -X go.szostok.io/version.version=v1.8.1+zapravila.20261006 -X go.szostok.io/version.commit=226c16b88e2a1982b89b9ce2aee4fc69a3e03d73 -X go.szostok.io/version.commitDate=2026-09-30T01:00:23Z -X go.szostok.io/version.buildDate=2026-10-06T00:00:00Z -X go.szostok.io/version.dirtyBuild=true' \
      -o /out/helmfile .

FROM alpine/helm:4.3.0@sha256:a6cf54599ccb99d90cf0712b30f03fdb3cab062e6b94e0418cc4db7e8a1464b2

RUN apk upgrade --update --no-cache && apk add --no-cache ruby git colordiff
COPY --from=helm-builder /out/helm /usr/bin/helm
COPY --from=helmfile-builder /out/helmfile /usr/local/bin/helmfile
COPY --from=helm-builder /source/LICENSE /usr/share/licenses/helm/LICENSE
COPY --from=helmfile-builder /source/LICENSE /usr/share/licenses/helmfile/LICENSE

WORKDIR /wd
COPY helmsnap.gemspec LICENSE.txt README.md ./
COPY lib/ ./lib/
COPY exe/ ./exe/
RUN gem install colorize && gem build && gem install helmsnap --local

ENTRYPOINT []
CMD []
