name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'tycooon/helmsnap'

    strategy:
      matrix:
        ruby: ["2.7", "3.0"]

    name: ${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rake

    # - uses: coverallsapp/github-action@v1.1.2
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
